version: '2'
services:
  app:
    build: .
    volumes:
      - .:/data
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8080"
  db:
    image: mysql:5.7.15
    env_file: ./env/mysql.env
    ports:
      - "3307:3306"
      